// TEAM APPLE!

#include "../../../pic24lib_all/esos/include/esos.h"
#include "../../../pic24lib_all/lib/include/pic24_adc.h"
#include "../../include/esos_f15_ui.h"
#include "../../include/esos_pic24_sensor.h"

ESOS_USER_TASK(READ_POT_SW1) {
  ESOS_TASK_BEGIN();
  static uint16_t u16_data;
  while(true) {
  	ESOS_TASK_F15UI_WAIT_UNTIL_SW1_PRESSED();
  	ESOS_USE_ADC_12_BIT(TRUE);
    ESOS_TASK_WAIT_ON_AVAILABLE_SENSOR(ESOS_SENSOR_CH02, ESOS_SENSOR_VREF_3V3);
    ESOS_TASK_WAIT_SENSOR_QUICK_READ(u16_data);
    ESOS_TASK_WAIT_UNTIL(ESOS_SENSOR_CLOSE());
    ESOS_TASK_WAIT_ON_AVAILABLE_OUT_COMM();
    ESOS_TASK_WAIT_ON_SEND_UINT32_AS_HEX_STRING((uint32_t)u16_data);
    ESOS_TASK_WAIT_ON_SEND_STRING("\n");
    ESOS_TASK_SIGNAL_AVAILABLE_OUT_COMM();
    ESOS_TASK_F15UI_WAIT_UNTIL_SW1_RELEASED();
  }
  ESOS_TASK_END();
}


ESOS_USER_TASK(READ_POT_SW2) {
  ESOS_TASK_BEGIN();
  static uint16_t u16_data;
  while(true) {
    ESOS_TASK_WAIT_ON_AVAILABLE_SENSOR(ESOS_SENSOR_CH02, ESOS_SENSOR_VREF_3V3);
    ESOS_USE_ADC_12_BIT(TRUE);
    ESOS_TASK_WAIT_SENSOR_READ(u16_data, ESOS_SENSOR_MAX64, ESOS_SENSOR_FORMAT_VOLTAGE);
    ESOS_TASK_WAIT_UNTIL(ESOS_SENSOR_CLOSE());
    ESOS_TASK_WAIT_ON_AVAILABLE_OUT_COMM();
    ESOS_TASK_WAIT_ON_SEND_STRING(" MAX VOLTAGE \n");
    ESOS_TASK_WAIT_ON_SEND_UINT32_AS_HEX_STRING((uint32_t)u16_data);
    ESOS_TASK_WAIT_ON_SEND_STRING("\n");
    ESOS_TASK_SIGNAL_AVAILABLE_OUT_COMM();
    ESOS_TASK_WAIT_TICKS(1000);
    ESOS_TASK_WAIT_ON_AVAILABLE_SENSOR(ESOS_SENSOR_CH02, ESOS_SENSOR_VREF_3V3);
    ESOS_USE_ADC_12_BIT(TRUE);
    ESOS_TASK_WAIT_SENSOR_READ(u16_data, ESOS_SENSOR_AVG64, ESOS_SENSOR_FORMAT_PERCENT);
    ESOS_TASK_WAIT_UNTIL(ESOS_SENSOR_CLOSE());
    ESOS_TASK_WAIT_ON_AVAILABLE_OUT_COMM();
    ESOS_TASK_WAIT_ON_SEND_STRING(" AVG PERCENT \n");
    ESOS_TASK_WAIT_ON_SEND_UINT32_AS_HEX_STRING((uint32_t)u16_data);
    ESOS_TASK_WAIT_ON_SEND_STRING("\n\n");
    ESOS_TASK_SIGNAL_AVAILABLE_OUT_COMM();
    ESOS_TASK_WAIT_TICKS(5000);
  }
  ESOS_TASK_END();
}

void user_init(void) {
  CONFIG_POT();
  config_esos_f15ui();
  f15ui_flashLED3(250);
  esos_RegisterTask(READ_POT_SW1);
  esos_RegisterTask(READ_POT_SW2);
}